// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `cmd2kcn.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <cmd2kcn.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __kelp__cmd2kcn__setNodeConfig_name = "setNodeConfig";

const ::std::string __kelp__cmd2kcn__setSelfConfig_name = "setSelfConfig";

const ::std::string __kelp__cmd2kcn__delNodeConfig_name = "delNodeConfig";

const ::std::string __kelp__cmd2kcn__delSelfConfig_name = "delSelfConfig";

}
::IceProxy::Ice::Object* ::IceProxy::kelp::upCast(::IceProxy::kelp::cmd2kcn* p) { return p; }

void
::IceProxy::kelp::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::kelp::cmd2kcn>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::kelp::cmd2kcn;
        v->__copyFrom(proxy);
    }
}

bool
IceProxy::kelp::cmd2kcn::setNodeConfig(const ::std::string& uuid, const ::std::string& key, const ::std::string& value, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __kelp__cmd2kcn__setNodeConfig_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__kelp__cmd2kcn__setNodeConfig_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::kelp::cmd2kcn* __del = dynamic_cast< ::IceDelegate::kelp::cmd2kcn*>(__delBase.get());
            return __del->setNodeConfig(uuid, key, value, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::kelp::cmd2kcn::begin_setNodeConfig(const ::std::string& uuid, const ::std::string& key, const ::std::string& value, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__kelp__cmd2kcn__setNodeConfig_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __kelp__cmd2kcn__setNodeConfig_name, __del, __cookie);
    try
    {
        __result->__prepare(__kelp__cmd2kcn__setNodeConfig_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(uuid);
        __os->write(key);
        __os->write(value);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::kelp::cmd2kcn::end_setNodeConfig(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __kelp__cmd2kcn__setNodeConfig_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

bool
IceProxy::kelp::cmd2kcn::setSelfConfig(const ::std::string& key, const ::std::string& value, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __kelp__cmd2kcn__setSelfConfig_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__kelp__cmd2kcn__setSelfConfig_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::kelp::cmd2kcn* __del = dynamic_cast< ::IceDelegate::kelp::cmd2kcn*>(__delBase.get());
            return __del->setSelfConfig(key, value, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::kelp::cmd2kcn::begin_setSelfConfig(const ::std::string& key, const ::std::string& value, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__kelp__cmd2kcn__setSelfConfig_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __kelp__cmd2kcn__setSelfConfig_name, __del, __cookie);
    try
    {
        __result->__prepare(__kelp__cmd2kcn__setSelfConfig_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(key);
        __os->write(value);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::kelp::cmd2kcn::end_setSelfConfig(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __kelp__cmd2kcn__setSelfConfig_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

bool
IceProxy::kelp::cmd2kcn::delNodeConfig(const ::std::string& uuid, const ::std::string& key, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __kelp__cmd2kcn__delNodeConfig_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__kelp__cmd2kcn__delNodeConfig_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::kelp::cmd2kcn* __del = dynamic_cast< ::IceDelegate::kelp::cmd2kcn*>(__delBase.get());
            return __del->delNodeConfig(uuid, key, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::kelp::cmd2kcn::begin_delNodeConfig(const ::std::string& uuid, const ::std::string& key, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__kelp__cmd2kcn__delNodeConfig_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __kelp__cmd2kcn__delNodeConfig_name, __del, __cookie);
    try
    {
        __result->__prepare(__kelp__cmd2kcn__delNodeConfig_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(uuid);
        __os->write(key);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::kelp::cmd2kcn::end_delNodeConfig(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __kelp__cmd2kcn__delNodeConfig_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

bool
IceProxy::kelp::cmd2kcn::delSelfConfig(const ::std::string& key, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __kelp__cmd2kcn__delSelfConfig_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__kelp__cmd2kcn__delSelfConfig_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::kelp::cmd2kcn* __del = dynamic_cast< ::IceDelegate::kelp::cmd2kcn*>(__delBase.get());
            return __del->delSelfConfig(key, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::kelp::cmd2kcn::begin_delSelfConfig(const ::std::string& key, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__kelp__cmd2kcn__delSelfConfig_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __kelp__cmd2kcn__delSelfConfig_name, __del, __cookie);
    try
    {
        __result->__prepare(__kelp__cmd2kcn__delSelfConfig_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(key);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::kelp::cmd2kcn::end_delSelfConfig(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __kelp__cmd2kcn__delSelfConfig_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::kelp::cmd2kcn::ice_staticId()
{
    return ::kelp::cmd2kcn::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::kelp::cmd2kcn::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::kelp::cmd2kcn);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::kelp::cmd2kcn::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::kelp::cmd2kcn);
}

::IceProxy::Ice::Object*
IceProxy::kelp::cmd2kcn::__newInstance() const
{
    return new cmd2kcn;
}

bool
IceDelegateM::kelp::cmd2kcn::setNodeConfig(const ::std::string& uuid, const ::std::string& key, const ::std::string& value, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __kelp__cmd2kcn__setNodeConfig_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(uuid);
        __os->write(key);
        __os->write(value);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::kelp::cmd2kcn::setSelfConfig(const ::std::string& key, const ::std::string& value, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __kelp__cmd2kcn__setSelfConfig_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(key);
        __os->write(value);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::kelp::cmd2kcn::delNodeConfig(const ::std::string& uuid, const ::std::string& key, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __kelp__cmd2kcn__delNodeConfig_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(uuid);
        __os->write(key);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::kelp::cmd2kcn::delSelfConfig(const ::std::string& key, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __kelp__cmd2kcn__delSelfConfig_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(key);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateD::kelp::cmd2kcn::setNodeConfig(const ::std::string& uuid, const ::std::string& key, const ::std::string& value, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::std::string& __p_uuid, const ::std::string& __p_key, const ::std::string& __p_value, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_uuid(__p_uuid),
            _m_key(__p_key),
            _m_value(__p_value)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::kelp::cmd2kcn* servant = dynamic_cast< ::kelp::cmd2kcn*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->setNodeConfig(_m_uuid, _m_key, _m_value, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::std::string& _m_uuid;
        const ::std::string& _m_key;
        const ::std::string& _m_value;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __kelp__cmd2kcn__setNodeConfig_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, uuid, key, value, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::kelp::cmd2kcn::setSelfConfig(const ::std::string& key, const ::std::string& value, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::std::string& __p_key, const ::std::string& __p_value, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_key(__p_key),
            _m_value(__p_value)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::kelp::cmd2kcn* servant = dynamic_cast< ::kelp::cmd2kcn*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->setSelfConfig(_m_key, _m_value, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::std::string& _m_key;
        const ::std::string& _m_value;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __kelp__cmd2kcn__setSelfConfig_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, key, value, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::kelp::cmd2kcn::delNodeConfig(const ::std::string& uuid, const ::std::string& key, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::std::string& __p_uuid, const ::std::string& __p_key, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_uuid(__p_uuid),
            _m_key(__p_key)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::kelp::cmd2kcn* servant = dynamic_cast< ::kelp::cmd2kcn*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->delNodeConfig(_m_uuid, _m_key, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::std::string& _m_uuid;
        const ::std::string& _m_key;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __kelp__cmd2kcn__delNodeConfig_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, uuid, key, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::kelp::cmd2kcn::delSelfConfig(const ::std::string& key, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::std::string& __p_key, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_key(__p_key)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::kelp::cmd2kcn* servant = dynamic_cast< ::kelp::cmd2kcn*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->delSelfConfig(_m_key, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::std::string& _m_key;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __kelp__cmd2kcn__delSelfConfig_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, key, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* kelp::upCast(::kelp::cmd2kcn* p) { return p; }

namespace
{
const ::std::string __kelp__cmd2kcn_ids[2] =
{
    "::Ice::Object",
    "::kelp::cmd2kcn"
};

}

bool
kelp::cmd2kcn::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__kelp__cmd2kcn_ids, __kelp__cmd2kcn_ids + 2, _s);
}

::std::vector< ::std::string>
kelp::cmd2kcn::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__kelp__cmd2kcn_ids[0], &__kelp__cmd2kcn_ids[2]);
}

const ::std::string&
kelp::cmd2kcn::ice_id(const ::Ice::Current&) const
{
    return __kelp__cmd2kcn_ids[1];
}

const ::std::string&
kelp::cmd2kcn::ice_staticId()
{
    return __kelp__cmd2kcn_ids[1];
}

::Ice::DispatchStatus
kelp::cmd2kcn::___setNodeConfig(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string uuid;
    ::std::string key;
    ::std::string value;
    __is->read(uuid);
    __is->read(key);
    __is->read(value);
    __inS.endReadParams();
    bool __ret = setNodeConfig(uuid, key, value, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
kelp::cmd2kcn::___setSelfConfig(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string key;
    ::std::string value;
    __is->read(key);
    __is->read(value);
    __inS.endReadParams();
    bool __ret = setSelfConfig(key, value, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
kelp::cmd2kcn::___delNodeConfig(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string uuid;
    ::std::string key;
    __is->read(uuid);
    __is->read(key);
    __inS.endReadParams();
    bool __ret = delNodeConfig(uuid, key, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
kelp::cmd2kcn::___delSelfConfig(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string key;
    __is->read(key);
    __inS.endReadParams();
    bool __ret = delSelfConfig(key, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __kelp__cmd2kcn_all[] =
{
    "delNodeConfig",
    "delSelfConfig",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "setNodeConfig",
    "setSelfConfig"
};

}

::Ice::DispatchStatus
kelp::cmd2kcn::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__kelp__cmd2kcn_all, __kelp__cmd2kcn_all + 8, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __kelp__cmd2kcn_all)
    {
        case 0:
        {
            return ___delNodeConfig(in, current);
        }
        case 1:
        {
            return ___delSelfConfig(in, current);
        }
        case 2:
        {
            return ___ice_id(in, current);
        }
        case 3:
        {
            return ___ice_ids(in, current);
        }
        case 4:
        {
            return ___ice_isA(in, current);
        }
        case 5:
        {
            return ___ice_ping(in, current);
        }
        case 6:
        {
            return ___setNodeConfig(in, current);
        }
        case 7:
        {
            return ___setSelfConfig(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
kelp::cmd2kcn::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
kelp::cmd2kcn::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
kelp::__patch(cmd2kcnPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::kelp::cmd2kcnPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::kelp::cmd2kcn::ice_staticId(), v);
    }
}
