// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `image_collector.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include "image_collector.h"
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __kelp__ImageCollector__GetImage_name = "GetImage";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::kelp::upCast(::IceProxy::kelp::ImageCollector* p) { return p; }

void
::IceProxy::kelp::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::kelp::ImageCollector>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::kelp::ImageCollector;
        v->__copyFrom(proxy);
    }
}

::kelp::ImageData
IceProxy::kelp::ImageCollector::GetImage(const ::std::string& path, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __kelp__ImageCollector__GetImage_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__kelp__ImageCollector__GetImage_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::kelp::ImageCollector* __del = dynamic_cast< ::IceDelegate::kelp::ImageCollector*>(__delBase.get());
            return __del->GetImage(path, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::kelp::ImageCollector::begin_GetImage(const ::std::string& path, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__kelp__ImageCollector__GetImage_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __kelp__ImageCollector__GetImage_name, __del, __cookie);
    try
    {
        __result->__prepare(__kelp__ImageCollector__GetImage_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(path);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::kelp::ImageData
IceProxy::kelp::ImageCollector::end_GetImage(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __kelp__ImageCollector__GetImage_name);
    ::kelp::ImageData __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::kelp::ImageCollector::ice_staticId()
{
    return ::kelp::ImageCollector::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::kelp::ImageCollector::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::kelp::ImageCollector);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::kelp::ImageCollector::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::kelp::ImageCollector);
}

::IceProxy::Ice::Object*
IceProxy::kelp::ImageCollector::__newInstance() const
{
    return new ImageCollector;
}

::kelp::ImageData
IceDelegateM::kelp::ImageCollector::GetImage(const ::std::string& path, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __kelp__ImageCollector__GetImage_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(path);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::kelp::ImageData __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::kelp::ImageData
IceDelegateD::kelp::ImageCollector::GetImage(const ::std::string& path, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::kelp::ImageData& __result, const ::std::string& __p_path, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_path(__p_path)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::kelp::ImageCollector* servant = dynamic_cast< ::kelp::ImageCollector*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->GetImage(_m_path, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::kelp::ImageData& _result;
        const ::std::string& _m_path;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __kelp__ImageCollector__GetImage_name, ::Ice::Normal, __context);
    ::kelp::ImageData __result;
    try
    {
        _DirectI __direct(__result, path, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* kelp::upCast(::kelp::ImageCollector* p) { return p; }

namespace
{
const ::std::string __kelp__ImageCollector_ids[2] =
{
    "::Ice::Object",
    "::kelp::ImageCollector"
};

}

bool
kelp::ImageCollector::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__kelp__ImageCollector_ids, __kelp__ImageCollector_ids + 2, _s);
}

::std::vector< ::std::string>
kelp::ImageCollector::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__kelp__ImageCollector_ids[0], &__kelp__ImageCollector_ids[2]);
}

const ::std::string&
kelp::ImageCollector::ice_id(const ::Ice::Current&) const
{
    return __kelp__ImageCollector_ids[1];
}

const ::std::string&
kelp::ImageCollector::ice_staticId()
{
    return __kelp__ImageCollector_ids[1];
}

::Ice::DispatchStatus
kelp::ImageCollector::___GetImage(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string path;
    __is->read(path);
    __inS.endReadParams();
    ::kelp::ImageData __ret = GetImage(path, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __kelp__ImageCollector_all[] =
{
    "GetImage",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
kelp::ImageCollector::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__kelp__ImageCollector_all, __kelp__ImageCollector_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __kelp__ImageCollector_all)
    {
        case 0:
        {
            return ___GetImage(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
kelp::ImageCollector::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
kelp::ImageCollector::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
kelp::__patch(ImageCollectorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::kelp::ImageCollectorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::kelp::ImageCollector::ice_staticId(), v);
    }
}
