// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `web2kcn.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __web2kcn_h__
#define __web2kcn_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <base_query_interface.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace kelp
{

class web2kcn;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::kelp::web2kcn>&);
::IceProxy::Ice::Object* upCast(::IceProxy::kelp::web2kcn*);

}

}

namespace kelp
{

class web2kcn;
bool operator==(const web2kcn&, const web2kcn&);
bool operator<(const web2kcn&, const web2kcn&);
::Ice::Object* upCast(::kelp::web2kcn*);
typedef ::IceInternal::Handle< ::kelp::web2kcn> web2kcnPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::kelp::web2kcn> web2kcnPrx;
void __patch(web2kcnPtr&, const ::Ice::ObjectPtr&);

}

namespace kelp
{

class Callback_web2kcn_Query_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_web2kcn_Query_Base> Callback_web2kcn_QueryPtr;

}

namespace IceProxy
{

namespace kelp
{

class web2kcn : virtual public ::IceProxy::Ice::Object
{
public:

    ::kelp::BinData Query(const ::std::string& uuid, const ::std::string& serName, const ::std::string& param)
    {
        return Query(uuid, serName, param, 0);
    }
    ::kelp::BinData Query(const ::std::string& uuid, const ::std::string& serName, const ::std::string& param, const ::Ice::Context& __ctx)
    {
        return Query(uuid, serName, param, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_Query(const ::std::string& uuid, const ::std::string& serName, const ::std::string& param, const ::IceInternal::Function<void (const ::kelp::BinData&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_Query(uuid, serName, param, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_Query(const ::std::string& uuid, const ::std::string& serName, const ::std::string& param, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_Query(uuid, serName, param, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_Query(const ::std::string& uuid, const ::std::string& serName, const ::std::string& param, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::kelp::BinData&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_Query(uuid, serName, param, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_Query(const ::std::string& uuid, const ::std::string& serName, const ::std::string& param, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_Query(uuid, serName, param, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_Query(const ::std::string& uuid, const ::std::string& serName, const ::std::string& param, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::kelp::BinData&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::kelp::BinData&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::kelp::web2kcnPrx __proxy = ::kelp::web2kcnPrx::uncheckedCast(__result->getProxy());
                ::kelp::BinData __ret;
                try
                {
                    __ret = __proxy->end_Query(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::kelp::BinData&)> _response;
        };
        return begin_Query(uuid, serName, param, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_Query(const ::std::string& uuid, const ::std::string& serName, const ::std::string& param)
    {
        return begin_Query(uuid, serName, param, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Query(const ::std::string& uuid, const ::std::string& serName, const ::std::string& param, const ::Ice::Context& __ctx)
    {
        return begin_Query(uuid, serName, param, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Query(const ::std::string& uuid, const ::std::string& serName, const ::std::string& param, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Query(uuid, serName, param, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Query(const ::std::string& uuid, const ::std::string& serName, const ::std::string& param, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Query(uuid, serName, param, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Query(const ::std::string& uuid, const ::std::string& serName, const ::std::string& param, const ::kelp::Callback_web2kcn_QueryPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Query(uuid, serName, param, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Query(const ::std::string& uuid, const ::std::string& serName, const ::std::string& param, const ::Ice::Context& __ctx, const ::kelp::Callback_web2kcn_QueryPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Query(uuid, serName, param, &__ctx, __del, __cookie);
    }

    ::kelp::BinData end_Query(const ::Ice::AsyncResultPtr&);
    
private:

    ::kelp::BinData Query(const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_Query(const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<web2kcn> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_secure(bool __secure) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_twoway() const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_oneway() const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_batchOneway() const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_datagram() const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_batchDatagram() const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_compress(bool __compress) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_timeout(int __timeout) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<web2kcn> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<web2kcn*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace kelp
{

class web2kcn : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::kelp::BinData Query(const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace kelp
{

class web2kcn : virtual public ::IceDelegate::kelp::web2kcn,
                virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::kelp::BinData Query(const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace kelp
{

class web2kcn : virtual public ::IceDelegate::kelp::web2kcn,
                virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::kelp::BinData Query(const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace kelp
{

class web2kcn : virtual public ::Ice::Object
{
public:

    typedef web2kcnPrx ProxyType;
    typedef web2kcnPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::kelp::BinData Query(const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___Query(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const web2kcn& l, const web2kcn& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const web2kcn& l, const web2kcn& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace kelp
{

template<class T>
class CallbackNC_web2kcn_Query : public Callback_web2kcn_Query_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::kelp::BinData&);

    CallbackNC_web2kcn_Query(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::kelp::web2kcnPrx __proxy = ::kelp::web2kcnPrx::uncheckedCast(__result->getProxy());
        ::kelp::BinData __ret;
        try
        {
            __ret = __proxy->end_Query(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_web2kcn_QueryPtr
newCallback_web2kcn_Query(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::kelp::BinData&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_web2kcn_Query<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_web2kcn_QueryPtr
newCallback_web2kcn_Query(T* instance, void (T::*cb)(const ::kelp::BinData&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_web2kcn_Query<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_web2kcn_Query : public Callback_web2kcn_Query_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::kelp::BinData&, const CT&);

    Callback_web2kcn_Query(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::kelp::web2kcnPrx __proxy = ::kelp::web2kcnPrx::uncheckedCast(__result->getProxy());
        ::kelp::BinData __ret;
        try
        {
            __ret = __proxy->end_Query(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_web2kcn_QueryPtr
newCallback_web2kcn_Query(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::kelp::BinData&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_web2kcn_Query<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_web2kcn_QueryPtr
newCallback_web2kcn_Query(T* instance, void (T::*cb)(const ::kelp::BinData&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_web2kcn_Query<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
